[project]
name = "DocAI"
version = "0.0.1"
description = "Document AI"
authors = [{ name = "Adrian Yeung", email = "yeungadrianjy@gmail.com" }]
readme = "README.md"
keywords = ['python']
requires-python = ">=3.11,<4.0"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "pydantic>=2.10.4",
    "python-calamine>=0.3.1",
    "python-docx>=1.1.2",
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
    "tox-uv>=1.11.3",
]

[project.urls]
Homepage = "https://yeungadrian.github.io/DocAI/"
Repository = "https://github.com/yeungadrian/DocAI"

[tool.ruff]
line-length = 108
fix = true

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "D", # pydocstyle
  "D213", # Multi-line docstring summary should start at the second line
  "D417", # Missing argument descriptions
  "E", # pycodestyle
  "EM", # flake8-errmsg
  "F", # Pyflakes
  "FBT", # flake8-boolean-trap
  "I", # isort,
  "N", # pep8-naming
  "PIE", # flake8-pie
  "PT", # flake8-pytest-style
  "PTH", # flake8-use-pathlib
  "SIM", # flake8-simplify
  "TID", # flake8-tidy-imports
  "TRY", # tryceratops
  "UP", # pyupgrade
  "W", # pycodestyle
]

ignore = [
  # pydocstyle: http://www.pydocstyle.org/en/stable/error_codes.html
  "D401", # Relax NumPy docstring convention: First line should be in imperative mood
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.pycodestyle]
max-doc-length = 108

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
files = ["docai", "tests"]
strict = true
enable_error_code = [
  "redundant-expr",
  "truthy-bool",
  "ignore-without-code",
]
disallow_untyped_decorators = false
